### ISSUE TITLE
require('nan') in 1.8.x isn't working on node 0.10.36

### ISSUE THREAD

**Issue by chmorgan** [iojs/nan#319]
$ node -e "require('nan')"

module.js:340
    throw err;
          ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:559:25)
    at startup (node.js:80:7)
    at node.js:929:3

Went back to nan 1.7.x and this works (and the dependencies that rely on it)

**Comment by csrl** [comment]
I can confirm - this broke our dependency chain also as it does not appear to be backwards compatible release.  Fails on node 0.12.2 as well.

**Comment by kkoopa** [comment]
Republished as 1.8.2.

#320
